version: "3"
services:
  yuno-postgres:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - SQL_SAFE_UPDATES=1
    image: pgvector/pgvector:pg16
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
  yuno-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
