/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents': typeof AgentsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/runs/'
    | '/skills/'
    | '/tools/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/workflows/$workflowId'
    | '/agents'
    | '/runs'
    | '/skills'
    | '/tools'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/runs/'
    | '/skills/'
    | '/tools/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
